### ISSUE TITLE
[제안] ESLint & Prettier 추가

### ISSUE THREAD

**Issue by JaeHye0k** [JaeHye0k/Youtube-Clone#15]
**어떤 문제가 있어서 어떤 기능이 필요한가요?**
서로 다른 코드 포멧 때문에 불필요한 파일 변경 사항이 발생합니다. 
예를 들어 A는 vscode prettier 확장에서 탭 너비를 4칸으로 설정하고 B는 탭 너비를 2칸으로 설정한 경우 prettier 의 자동 포멧팅 기능 때문에 탭 너비가 수정되어 불필요한 수정 사항이 발생하게 됩니다.

**해당 문제를 어떻게 해결할 수 있나요?**
ESLint, Prettier, VSCode 의 설정 파일을 만들어서 해당 프로젝트에서 일관된 코드 컨벤션을 지킬 수 있습니다.

한 분이라도 동의하시면 설정 파일 세팅해서 PR 올리겠습니다.

**Comment by Youjin-K** [comment]
동의합니다.
