### ISSUE TITLE
[수정 요청] 사이드바 반응형에 따른 메인 페이지 반응형 수정 요청

### ISSUE THREAD

**Issue by JaeHye0k** [JaeHye0k/Youtube-Clone#33]
## 어떤 문제가 있나요?
아래 이미지처럼 사이드바는 max-width: 1312px 에서 접히고, max-width: 791px 에서 아예 사라집니다. 
그러나 MainPageContainer의 left 가 이에 맞게 조정되지 않아 여백이 생깁니다.
![스크린샷 2024-12-20 073236](https://github.com/user-attachments/assets/34c2d13e-1fe9-4e50-9568-e62729b68d5c)
![image](https://github.com/user-attachments/assets/41b031a1-1cea-4828-84a6-4347a41b0fa5)

* 데스크탑 사이즈에서 접속하고 이후에 화면이 작아졌을 때는 여백 없이 잘 동작하지만, 테블릿&모바일 사이즈인 상태에서 접속했을 때는 위 이미지처럼 여백이 생깁니다.

## 해당 문제를 어떻게 해결할 수 있나요?
현재 MainPageContainer 컴포넌트에서는 left를 다음과 같이 조정해주고 있는 것 같습니다.
- isSidebarOpen가 true일 때는 left: 240px
- isSidebarOpen이 false일 때는 left: 72px

그러나 사이드바 컴포넌트는 데스크탑과, 테블릿&모바일 환경이 다르게 동작하기 때문에 두 개로 분리하여 관리하고 있습니다.
- 데스크탑 사이드바 - <DesktopSidebar />
- 테블릿&모바일 사이드바 - <Sidebar />
(이름을 명확하게 구분하지 않은 점 죄송합니다.)

따라서 사이드바의 상태도 `useLayoutStore`에서 `isDesktopSidebarOpen`과 `isSidebarOpen`을 독립적으로 관리하고 있습니다. 즉, 데스크탑 사이즈에서 사이드바를 닫아놓고, 태블릿&모바일 사이즈에서 사이드바를 열어도 다시 데이크탑 사이즈로 돌아오면 사이드바는 닫혀있습니다.

실제 유튜브를 보니 데스크톱 환경에서는 사이드바의 열림, 닫힘 여부에 따라 MainPageContainer 컴포넌트의 left가 조정되지만, 테블릿&모바일 환경에서는 사이드바의 열림, 닫힘 여부를 신경쓰지 않고 left가 고정적이더라구요.

따라서 MainPageContainer 의 스타일을 다음과 같이 수정하면 해결되지 않을까 생각합니다.
```ts
const MainPageContainer = styled.div<{ $isSidebarOpen: boolean }>`
    position: fixed;
    top: 56px;
    left: ${({ $isSidebarDesktopOpen }) => ($isSidebarDesktopOpen ? '240px' : '72px')};
    right: 0;
    bottom: 0;
    z-index: 1;
    transition: left 0.2s;
    @media screen and (${({theme})=>theme.mediaQuery.sidebar.tablet}) {
         left: 72px;
    }
    @media screen and (${({theme})=>theme.mediaQuery.sidebar.mobile}) {
         left: 0px;
    }
`;
```

**Comment by Youjin-K** [comment]
제 로컬에서는 화면에 여백이 생기지 않고 있어서 다른 분들께 그렇게 보이는지 몰랐네요,, 😞

![image](https://github.com/user-attachments/assets/99ded033-9470-47bf-a77e-b05c60ba0a05)
![image](https://github.com/user-attachments/assets/841dc1f0-7f05-4822-8073-d76ae7ca1401)

 수정 요청 제안해주셔서 감사합니다!
